id: P006783
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:22:41.696041
source_metadata:
  id: bdr:W22092
  title: སྤར་ཁའི་གཏོ་བརྒྱད་དང་གཏོ་ཐབས་སྐོར།
  author: ''
  volumes:
    ed90e5f4af954cadbc0c2b91b031d017:
      image_group_id: I1KG9798
      title: ''
      volume_number: 1
      total_pages: 540
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
