id: P006783
initial_creation_type: ocr
source_metadata:
  id: bdr:W22092
  title: སྤར་ཁའི་གཏོ་བརྒྱད་དང་གཏོ་ཐབས་སྐོར།
  author: ''
  volumes:
    ed90e5f4af954cadbc0c2b91b031d017:
      image_group_id: I1KG9798
      title: ''
      volume_number: 1
      total_pages: 540
      base_file: v001.txt
