id: IBAECC86D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T20:56:18+00:00'
last_modified: '2022-06-08T06:49:43.000546+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22092
  title: སྤར་ཁའི་གཏོ་བརྒྱད་དང་གཏོ་ཐབས་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    ED3B:
      image_group_id: I1KG9798
      title: ''
      total_pages: 540
      order: 1
      base_file: ED3B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
